### ISSUE TITLE
Bug in DateTime when adding an appointment

### ISSUE THREAD

**Issue by thutahw** [AY2021S1-CS2103T-W12-3/tp#155]
Instead of showing the invalid command message, error is shown when the time is not specified in the` DateTime` entered by the user.  

Expected format: dt/19-05-2020 12:00

![image](https://user-images.githubusercontent.com/66032473/97154563-feb5ae80-17ae-11eb-8703-0263cbe3840f.png)

**Comment by porkeypine** [comment]
Fixed in PR 'Add DeleteAppointmentCommand'
